from pathlib import Path

ROOT_DIRECTORY_PATH = Path(__file__).parent.absolute()
DATA_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "data"
RAW_DATA_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "data" / "raw"
PROCESSED_DATA_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "data" / "processed"
METRICS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "metrics"
MODELS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "models"
REPORTS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "reports"
FEATURES_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "features"
DASHBOARD_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "dashboard"
INTERACTIVE_REPORTS_PATH = ROOT_DIRECTORY_PATH.parent / "interactive_reports"
IMGS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "imgs"
SCRIPTS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "scripts"
NOTEBOOKS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "notebooks"
DATABASE_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / "database"
API_ROUTES_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "routers"
API_SERVICES_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "services"
API_SCHEMAS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "schemas"
